version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-to-web:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          -run: 
            command: surge --project ../public --domain georgefloyd.help
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy-to-web:
          filters:
            branches:
              only: mg-add-ci
