version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-to-web:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx surge --project ./public --domain ${DOMAIN_NAME}
workflows:
    test:
      jobs:
        - test
      
    deploy-to-web:
      jobs:
        - deploy-to-web:
            filters:
              branches:
                only: prod
